export const siteConfig = {
  site: {
    name: 'Gift Basket',
    tagline: 'Personalized & Artisanal Gift Collections',
    logo: 'https://qobo-zip-storage.s3.us-east-1.amazonaws.com/logos/1774287894327-8a8da7b9a9d5ff77.919987732895',
    contact: {
      phone: '+1 (555) 234-5678',
      email: 'hello@giftbasket.com',
      address: '456 Artisan Lane, Portland, OR 97214',
    },
    social: {
      facebook: 'https://facebook.com/giftbasket',
      instagram: 'https://instagram.com/giftbasket',
      twitter: 'https://twitter.com/giftbasket',
      linkedin: '',
      youtube: 'https://youtube.com/giftbasket',
    },
  },
  theme: {
    primary: '#D4785C',
    primaryLight: '#E8A89E',
    primaryDark: '#A0533F',
    secondary: '#6B4E71',
    accent: '#F4A261',
    background: '#FFFFFF',
    backgroundLight: '#FEF9F3',
    text: '#2D2D2D',
    textLight: '#6B7280',
    border: '#E8D5C4',
    fontSans: "'Poppins', system-ui, sans-serif",
    fontDisplay: "'Playfair Display', serif",
    currency: '$',
  },
  content: {
    common: {
      addToCart: 'Add to Basket',
      viewDetails: 'View Details',
    },
    nav: {
      officialStoreText: 'Official Gift Basket',
    },
    home: { 
      heroTitle: 'Handcrafted Gifts for Every Occasion',
      heroSubtitle: 'Discover beautifully curated gift baskets filled with artisanal products. From personalized touches to specialty selections, find the perfect present.',
      heroCtaText: 'Browse Baskets',
      heroCtaLink: '/shop',
      newCollectionTag: 'New Collection',
      featuredTag: 'Customer Favorite',
      featuredTitle: 'Most Loved Baskets',
      featuredSubtitle: 'Hand-selected collections curated with care and attention to detail.',
      valuesTag: 'Why Gift Basket',
      valuesTitle: 'Thoughtful Gifting Made Easy',
      valuesSubtitle: 'Premium artisanal products wrapped with love and personalization.',
      ctaTitle: 'Celebrate Every Moment',
      ctaSubtitle: 'Make memories special with our personalized gift baskets. Perfect for birthdays, anniversaries, and every milestone.',
      ctaButtonText: 'Shop All Baskets',
      ctaContactText: 'Contact Us',
    },
    shop: {
      title: 'Our Gift Collections',
      subtitle: 'Explore our curated selection of artisanal gift baskets',
      filterTitle: 'Filters',
      categoryTitle: 'Occasion',
      priceTitle: 'Price Range',
      sortTitle: 'Sort By',
      noProducts: 'No gift baskets found',
      productsFound: 'baskets found',
    },
    product: {
      selectSize: 'Select Size',
      quantity: 'Quantity',
      addToCart: 'Add to Basket',
      descriptionTitle: 'About This Basket',
      relatedTitle: 'Similar Gifts',
      freeShippingText: 'Free shipping on orders above',
      returnsText: 'Easy returns and exchanges within 14 days',
      securePaymentText: '100% secure payment processing',
    },
    cart: {
      title: 'Your Gift Basket',
      emptyTitle: 'Your Basket is Empty',
      emptySubtitle: 'Explore our collections and find the perfect gift',
      continueShopping: 'Continue Shopping',
      summaryTitle: 'Order Summary',
      itemsLabel: 'Items',
      shippingLabel: 'Shipping',
      totalLabel: 'Total',
      checkoutButton: 'Proceed to Checkout',
    },
    checkout: {
      title: 'Secure Checkout',
      deliveryTitle: 'Delivery Details',
      paymentTitle: 'Payment Method',
      orderSummaryTitle: 'Order Summary',
      placeOrderButton: 'Complete Purchase',
      processingButton: 'Processing...',
    },
    orderConfirmation: {
      title: 'Gift Order Confirmed!',
      subtitle: "Thank you for your purchase. We'll send you a confirmation email and begin preparing your beautiful gift.",
      orderNumberLabel: 'Order Number',
      statusLabel: 'Status',
      itemsTitle: 'Gift Baskets Ordered',
      addressTitle: 'Delivery Address',
      contactTitle: 'Contact Info',
      continueButton: 'Continue Shopping',
      trackButton: 'Track Order',
    },
    trackOrder: {
      title: 'Track Your Gift',
      subtitle: 'Enter your Order ID and Email to see your gift delivery status',
      orderIdLabel: 'Order ID',
      emailLabel: 'Email',
      buttonText: 'Track Order',
      searchAgain: 'Search Again',
      progressTitle: 'Delivery Progress',
      itemsTitle: 'Gift Baskets',
      addressTitle: 'Delivery Address',
    },
    auth: {
      loginTitle: 'Welcome Back',
      loginSubtitle: 'Login to your account to track orders and manage your gift preferences.',
      registerTitle: 'Create Account',
      registerSubtitle: 'Join our community and enjoy personalized gifting experiences.',
      emailLabel: 'Email Address',
      passwordLabel: 'Password',
      nameLabel: 'Full Name',
      loginButton: 'Login',
      registerButton: 'Create Account',
      noAccount: "Don't have an account?",
      hasAccount: 'Already have an account?',
      registerLink: 'Register',
      loginLink: 'Login',
      trackGuest: 'Track order without login',
    },
    contact: {
      title: 'Get in Touch',
      subtitle: "Have questions about our gift baskets? We'd love to help you find the perfect gift.",
      infoTitle: 'Contact Information',
      infoSubtitle: 'Reach out through any of these channels and our team will respond promptly.',
      formName: 'Full Name',
      formEmail: 'Email',
      formSubject: 'Subject',
      formMessage: 'Message',
      formButton: 'Send Message',
      formSuccess: 'Thank you! Your message has been sent successfully. We will be in touch soon.',
    },
    footer: {
      description: 'Crafting beautiful, personalized gift baskets with artisanal products and thoughtful touches since 2015.',
      newsletterTitle: 'Subscribe',
      newsletterSubtitle: 'Get exclusive offers, new collections, and gifting inspiration.',
    }
  },
  products: [
    { id: 1, name: 'Artisan Coffee & Treats Basket', slug: 'artisan-coffee-treats-basket', category: 'Coffee Lovers', price: 7999, discount_price: 5999, image: 'https://images.unsplash.com/photo-1599599810694-b5ac4dd53c4f?auto=format&fit=crop&w=800&q=80', description: 'Premium curated basket featuring specialty coffee beans, gourmet biscuits, and artisanal treats.', sizes: ['Standard', 'Deluxe'], featured: true, inStock: true },
    { id: 2, name: 'Luxury Spa & Wellness Retreat', slug: 'luxury-spa-wellness-basket', category: 'Wellness', price: 9999, discount_price: 7499, image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=800&q=80', description: 'Indulgent spa basket with organic bath products, scented candles, and aromatherapy essentials.', sizes: ['Standard', 'Premium'], featured: true, inStock: true },
    { id: 3, name: 'Gourmet Wine & Cheese Collection', slug: 'wine-cheese-collection', category: 'Wine & Spirits', price: 12999, discount_price: 9999, image: 'https://images.unsplash.com/photo-1510812431401-41d2cab2707d?auto=format&fit=crop&w=800&q=80', description: 'Elegant selection of fine wine paired with premium artisanal cheeses and crackers.', sizes: ['Standard', 'Deluxe'], featured: true, inStock: true },
    { id: 4, name: 'Personalized Letterpress Gift Set', slug: 'personalized-letterpress-set', category: 'Personalized', price: 5499, discount_price: null, image: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=800&q=80', description: 'Custom letterpress stationery, personalized notecards, and hand-calligraphy gift wrapping.', sizes: ['One Size'], featured: false, inStock: true },
    { id: 5, name: 'Gourmet Chocolate & Champagne Box', slug: 'chocolate-champagne-box', category: 'Celebration', price: 6999, discount_price: 4999, image: 'https://images.unsplash.com/photo-1522200770667-dda76efd00c1?auto=format&fit=crop&w=800&q=80', description: 'Artisan chocolates paired with premium champagne for the perfect celebration gift.', sizes: ['Standard', 'Deluxe'], featured: true, inStock: true },
  ],
  categories: [
    { id: 1, name: 'Coffee Lovers', slug: 'coffee-lovers' },
    { id: 2, name: 'Wellness', slug: 'wellness' },
    { id: 3, name: 'Wine & Spirits', slug: 'wine-spirits' },
    { id: 4, name: 'Personalized', slug: 'personalized' },
    { id: 5, name: 'Celebration', slug: 'celebration' },
    { id: 6, name: 'Gourmet', slug: 'gourmet' },
  ],
  subcategories: [
    { id: 1, categoryId: 1, name: 'Single Origin', slug: 'single-origin' },
    { id: 2, categoryId: 1, name: 'Coffee & Tea Blend', slug: 'coffee-tea-blend' },
    { id: 3, categoryId: 2, name: 'Bath & Body', slug: 'bath-body' },
    { id: 4, categoryId: 2, name: 'Aromatherapy', slug: 'aromatherapy' },
  ],
  heroSections: [
    { id: 1, title: 'Handcrafted Gifts for Every Occasion', subtitle: 'Discover beautifully curated gift baskets filled with artisanal products. Personalized touches make every gift special.', cta_text: 'Browse Baskets', cta_link: '/shop', background_image_url: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=1600&q=80', published: true },
    { id: 2, title: 'New Artisanal Collections', subtitle: 'Explore our latest carefully curated selections featuring specialty items from independent makers.', cta_text: 'Explore', cta_link: '/shop', background_image_url: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=1600&q=80', published: true },
    { id: 3, title: 'Seasonal Gift Specials', subtitle: 'Limited edition baskets featuring seasonal favorites and exclusive artisanal finds. Order early for the holidays.', cta_text: 'Shop Limited Edition', cta_link: '/shop', background_image_url: 'https://images.unsplash.com/photo-1464207687429-7505649dae38?auto=format&fit=crop&w=1600&q=80', published: true },
  ],
  featureBlocks: [
    { id: 1, title: 'Free Personalization', description: 'Add custom messages and gift cards to every basket', icon: 'Heart', display_order: 1, published: true },
    { id: 2, title: 'Secure Payment', description: '100% secure checkout with encrypted processing', icon: 'Shield', display_order: 2, published: true },
    { id: 3, title: 'Fast Delivery', description: 'Express shipping available for last-minute gifts', icon: 'Truck', display_order: 3, published: true },
    { id: 4, title: 'Artisanal Quality', description: 'Hand-selected premium and specialty products', icon: 'Sparkles', display_order: 4, published: true },
  ],
  settings: {
    site_name: 'Gift Basket',
    site_logo: 'https://qobo-zip-storage.s3.us-east-1.amazonaws.com/logos/1774287894327-8a8da7b9a9d5ff77.919987732895',
    contact_phone: '+1 (555) 234-5678',
    contact_email: 'hello@giftbasket.com',
    address: '456 Artisan Lane, Portland, OR 97214',
    social_facebook: 'https://facebook.com/giftbasket',
    social_x: 'https://twitter.com/giftbasket',
    social_instagram: 'https://instagram.com/giftbasket',
    social_linkedin: '',
    social_youtube: 'https://youtube.com/giftbasket',
    shipping_charge: '10',
    tax_rate: '8.5',
    tax_name: 'Sales Tax',
    free_shipping_threshold: '75',
  },
  paymentSettings: {
    upi_qr_code_url: '',
    upi_number: '',
    instructions: 'Multiple payment options available including credit cards, debit cards, and digital wallets.',
    is_active: true,
  },
};

// Re-export for API compatibility (api.js expects these shapes)
export const fashionProducts = siteConfig.products.map((p) => ({ ...p, image_url: p.image || p.image_url, published: p.inStock !== false }));
export const categories = siteConfig.categories;
export const orders = [];
export const heroSections = siteConfig.heroSections;
export const featureBlocks = siteConfig.featureBlocks;
export const contactMessages = [];
export const settings = [siteConfig.settings];
export const paymentSettings = [{ id: '1', ...siteConfig.paymentSettings }];